In [12]:
import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Define the dimensions of the input, hidden, and output layers
input_dim = 5
hidden_dim = 50
output_dim = 3

# Instantiate the MLP model
model = MLP(input_dim, hidden_dim, output_dim)

# Define the loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# Generate some example input data
input_data = torch.randn(1, input_dim)
print(input_data)

# Forward pass
output = model(input_data)
print(output)

# Compute the loss
target = torch.randn(1, output_dim)
print(target)

loss = criterion(output, target)

# Backward pass and update weights
optimizer.zero_grad()
loss.backward()
optimizer.step()


tensor([[ 0.9106,  0.2409, -2.0157, -1.1464,  0.1012]])
tensor([[0.1706, 0.0104, 0.2546]], grad_fn=<AddmmBackward0>)
tensor([[-1.1839,  0.2496, -1.6516]])
